### ISSUE TITLE
下载下来 依赖都装不了

### ISSUE THREAD

**Issue by bigGoodMan** [zhouyupeng/webpack4.x_demo#4]
我的是mac
兄弟 你这个拉下来之后依赖装不了。把package-lock.json删掉，依赖能装了。但是不能打包就报错
![image](https://user-images.githubusercontent.com/21271880/58364978-9eeb1200-7eef-11e9-96fb-91272c11dba2.png)

**Comment by Haidy1987** [comment]
![image](https://user-images.githubusercontent.com/20874923/58745768-a5493300-8487-11e9-96d1-3d13966f0087.png)
